json-c/json-c

json_util.c
json_util.h

Also refactor json_object_from_file to use json_object_from_fd
internally.
Signed-off-by: Michael Heimpold <mhei@heimpold.de>

Introduce json_object_from_fd

---

json_object.c
json_object.h

- Tabs are easier to read for tired eyes and editor adjustable

Adding JSON_C_TO_STRING_PRETTY_TAB flag

---

json_object.h

This PR simply applies the compiler warnings fix I made against the release branch to master

Apply compile warning fix to master branch

---

json_object.c

Minor changes to make it build in Visual Studio: VS2015, VS2012, Windows SDK 7.1
CI results: https://ci.appveyor.com/project/Nzbuu/json-c/build/fix_vs_build.15

Fix build in Visual Studio

---

tests/test-defs.sh
tests/test1.c
tests/test2.c
tests/test4.c
tests/test_null.c
tests/test_parse.c
tests/test_util_file.c

- C89 comment > C99 comment
- Less long lines (for small screens and see 2 files as the same with a "multiple panels" feature like the one in GNU Emacs and Qt Creator)
- return STDC_CONST for main
- Errors to stderr
- Other things

Very minor changes to some tests

---

json_object.c
json_tokener.c
linkhash.c

Add FALLTHRU comment to handle GCC7 warnings.

---

tests/test4.test
tests/testReplaceExisting.test
tests/test_basic.test
tests/test_cast.test
tests/test_charcase.test
tests/test_compare.test
tests/test_double_serializer.test
tests/test_float.test
tests/test_json_pointer.test
tests/test_locale.test
tests/test_null.test
tests/test_parse.test
tests/test_parse_int64.test
tests/test_printbuf.test
tests/test_set_serializer.test
tests/test_set_value.test
tests/test_visit.test

tests: symlink basic tests to a single file that has the common code

---

README.md

Looks nice to see a `Build Passing` tag when you
scroll to the README.

README.md: show build status tag from travis-ci.org

---

.gitignore
Makefile.am

Just a tweak so that `make distcheck` passes for distribution.

Fix makedist

---

json_util.c
strerror_override.h

Should fix build with Visual Studio.

build: fix build on appveyor CI

---

json_tokener.c
tests/testReplaceExisting.c
tests/testReplaceExisting.expected
tests/test_parse.c
tests/test_parse.expected

PR content:
- Fixed test compilation
- Improved tests for this case
- Fixed json parsing issue on -Infinity

Json-c 0.12: Fixed Infinity bug

---

json_object.c
json_object.h

json_object: Add const size_t json_c_object_sizeof()

---

README.md

README.md:fix dead "file.html" link

---

json_object.c
json_object.h

I also added a couple trivial, but related, suggestions.
closes #460

json_object.h:document json_object_new_string_len()

---

json_object.c
json_tokener.h

json_object.c:set errno in json_object_get_double()

---

configure.ac
tests/test_deep_copy.c
tests/test_double_serializer.c

a likely more welcome change than #490 based on comments in #489 
closes #489

build: add option --disable-werror to configure

---

.travis.yml

.travis.yml:test on more recent clang and gcc versions

---

tests/test_visit.c
tests/test_visit.expected

update json_visit testcase

---

json_object.c
json_object.h
tests/test1.c
tests/test1.expected
tests/test1Formatted_plain.expected
tests/test1Formatted_pretty.expected
tests/test1Formatted_spaced.expected
tests/test1Formatted_spaced_pretty.expected
tests/test1Formatted_spaced_pretty_pretty_tab.expected

add json_object_new_null()

---

json_tokener.c
json_tokener.h
tests/test_parse.c
tests/test_parse.expected

plan 2: validate utf-8 string  during parsing string.  #122 
Validate fuction has been added into macro `PEEK_CHAR(dest, tok)` .

validate utf-8 string  

---

CMakeLists.txt

Add distcheck target in cmake.
+ ```cmake ..```
+ ```make distcheck```

Increase distcheck target in cmake

---

CMakeLists.txt
README.md

Add uninstall target in cmake

---

CMakeLists.txt
json_object.c
json_object.h

See: https://stackoverflow.com/questions/42125/function-declaration-isnt-a-prototype

Enforce strict prototypes.

---

tests/test1.c
tests/test1.expected
tests/test1Formatted_plain.expected
tests/test1Formatted_pretty.expected
tests/test1Formatted_spaced.expected
tests/test1Formatted_spaced_pretty.expected
tests/test1Formatted_spaced_pretty_pretty_tab.expected

Increased the test coverage of array_list.c from 73.7% to 94.7%

Arraylist testcase

---

random_seed.c

Some CPUs advertise `RDRAND` in `CPUID`, but return `0xFFFFFFFF`
unconditionally. To avoid locking up later, test `RDRAND` during
initialization, and if it returns `0xFFFFFFFF`, mark it as nonexistent.
Fixes #588.

Detect broken RDRAND during initialization

---

CMakeLists.txt
README.md
cmake-configure

Support to build both static and shared libraries

---

apps/json_parse.c

json_parse demo: fix and use usage() function

---

json_util.c
json_util.h
tests/test_parse_int64.expected

fix json_parse_uint64() usage of errno

---

tests/test_deep_copy.c

test_deep_copy: Fix assertion value.

---

random_seed.c

there is no need to call CryptAcquireContextW because two string parameters are NULL
CryptAcquireContextW does not work on Win98, and CRYPT_SILENT flags is not supported on WInNT4 and Win98x, any info about WIn2k?
I'm returning the fallback function, if you don't like it it can be reverted, but anyway is a bad pratice to call exit() inside a library

get_cryptgenrandom_seed: compat with old windows + fallback

---

json_tokener.c
json_tokener.h
tests/test_parse.c
tests/test_parse.expected

fix issue 616: support the surrogate pair in split file.

---

json_object.c

Fixes https://github.com/json-c/json-c/issues/647

Fix "may be used uninitialized" Release build failure

---

apps/json_parse.c

Resolves https://github.com/json-c/json-c/issues/654

json_parse: Fix read past end of buffer

---

random_seed.c

instead of exiting the process
fixes https://github.com/json-c/json-c/issues/672

random_seed: on error, continue to next method

---

json_object.c

I believe your checks are not correct.
in my opinion they are equivalent to checks !=.
I suggest a simple fix.

fix invalid unsigned arithmetic.

---

json_object.c
json_object_private.h
json_tokener.c
json_util.c
json_util.h
tests/test_deep_copy.c
tests/test_deep_copy.expected

Around 40% speedup for 32-bit x86 and around 20% speedup for 64-bit x86.

Speed up parsing and object creation

---

json_object.c

If memory allocation fails in json_c_set_serialization_double_format or
json_object_copy_serializer_data then return with an error value and
preserve previous values without overriding them with NULL.

Preserve context if out of memory

---

README.md

it could be necessary to execute make install

Small update to README file

---

snprintf_compat.h

Solution: fix it to reflect what's happening properly

Problem: confusing error message in snprintf_compat.h

---

json_object.h

docs: micro typo in json_object_put doc

---

CMakeLists.txt

Hi, would it be possible to build pkg-config for MSVC targets as well?

Build pkg-config for msvc as well

---

apps/CMakeLists.txt

Update the min version to match parent CMakeLists.txt 3.9...3.12

Allow build with cmake 4.0.0
