arraylist.c, arraylist.h, json_object.c, json_object.h
Arrays can already be sorted with json_object_array_sort() which uses
qsort() of the standard C library. This adds a counterpart using the
bsearch() from C.
=> add bsearch for arrays

json_tokener.c, tests/test_parse.c, tests/test_parse.expected
Some badly formated "numbers" could get partly parsed, resulting in truncated results instead of raising an error.
Examples :
'1.2.3'      -> (double)1.2
'2015-01-15' -> (int)2015
Here is a first fix. It is not perfect (example: input can still end with a 'E', which is forbidden by http://json.org doc) but should avoid most non-sensically formated input.
The goal of this patch is to get submitted into Debian bugtracking system and hopefully integrated before the next release. Could you review it ?
A few tests added.
PS: If you are interested, I could continue to make it more strict for cases like '7f020e68a7' or '0x12345'. Currently, json_tokener_parse_ex() tries to return something although they are clear cases of invalid input. A number can only be followed by ',', '}' or ']' (and …
=> Tightening the number parsing algorithm

configure.ac, json-c.pc.in
In certain C libraries (e.g uClibc), isnan() and related functions are
implemented in libm, so json-c needs to link against it. This commit
therefore adds an AC_TRY_LINK() test to check whether a program
calling isnan() can be properly linked with no special flags. If not,
we assume linking against libm is needed.
The json-c.pc.in file is also adjusted so that in the case of static
linking against json-c, -lm is also used.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
=> Link against libm when needed

json_object.h
The json_object_object_foreach macro has a couple of compiler warnings when compiled with the most pedantic of warning flags set.  This pull requests fixes those warnings.
=> Fix compiler warnings

.gitignore, config.h.in, config.h.win32, json-c.vcxproj, json-c.vcxproj.filters, json_config.h.win32, json_inttypes.h, json_object.c, json_tokener.c, linkhash.c, math_compat.h, random_seed.c
Update config.h.win32 and json_config.h.win32 for vs2010/winsdk71 as well
Update build configurations for vs2010/winsdk71
Add x64 build configurations
Simplified json_inttypes.h and math_compat.h
Seems to build successfully with all combinations of the following settings:
* Debug and Release configurations
* win32 and win64 targets
* winsdk71 and vs2013 platforms
Includes some changes from https://github.com/json-c/json-c/pull/164
=> Update configuration for VS2010 and win64

Makefile.am
The last json_tokener_errors change affects the binary package, we need a bump to solve the issue.
See [this bug of postgis.](https://bugzilla.redhat.com/show_bug.cgi?id=1123785)
=> SONAME bump

configure.ac
- ./configure fails due to bad code generation
On SLES 11.3:
```bash
92 [master] /> ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:32: installing `./compile'
configure.ac:78: installing …
```
=> Syntax error

json_object.c, json_object.h, json_object_private.h, linkhash.c, linkhash.h
This PR contains performance improvements which are especially useful for high performance applications (I use json-c in rsyslog, among others). This PR will probably be amended by more improvements (depending on when it is merged). Please let me know any concerns you may have.
=> Performance improvements

.travis.yml, appveyor.yml
Added build scripts for:
* Travis CI (Linux + OSX) https://travis-ci.org/Nzbuu/json-c
* Appveyor (Windows) https://ci.appveyor.com/project/Nzbuu/json-c
Windows build fails due to error fixed in PR #199.
=> Add build scripts for CI platforms

linkhash.c
Commit 2d549662be832da838aa063da2efa78ee3b99668 introduced read-only keys, but when the hash table
was resized, that attribute was not preserved. This resulted in
an invalid free at time of table destruction.
=> fix regression from 2d549662be832da838aa063da2efa78ee3b99668

arraylist.c, json_object.c, json_tokener.c
This fix errors that can happen when ingesting very large JSON files
when hitting the maximum heap size of the process.
=> Fix various potential null ptr deref and int32 overflows

configure.ac
The [AC_PROG_CC_C99 macro](https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/C-Compiler.html) sets the complier to the C99 standard if the compiler does not default to such behaviour (albeit gnu99). This is better than specifically hardcoding flags
=> Use a macro to indicate C99 to the compiler

configure.ac
AC_FUNC_REALLOC is messed up when cross-compiling, ending up in failed
build with "undefined reference to `rpl_realloc'" error.
AC_CHECK_FUNCS will work both with "usual" and cross builds.
= More Info =
The build fails with:
> make[2]: Entering directory '/home/jehan/dev/src/json-c'
CCLD     libjson-c.la
.libs/arraylist.o: In function `array_list_expand_internal':
/home/jehan/dev/src/json-c/arraylist.c:68: undefined reference to `rpl_realloc'
.libs/printbuf.o: In function `printbuf_extend':
/home/jehan/dev/src/json-c/printbuf.c:73: undefined reference to `rpl_realloc'
collect2: error: ld returned 1 exit status
Makefile:542: recipe for target 'libjson-c.la' failed
make[2]: *** [libjson-c.la] Error 1
make[2]: Leaving directory '/home/jehan/dev/src/json-c'
Makefile:640: recipe for target …
=> configure: check realloc with AC_CHECK_FUNCS() to fix cross-compilation.

arraylist.c, arraylist.h, json_object.c, json_object.h
array_list_del_idx lets you delete a number of elements from an array list starting at a specified index. json_object_array_del_idx uses array_list_del_idx to do the same thing for json object arrays.
=> Added array_list_del_idx and json_object_array_del_idx

json_object.c, json_object.h
Using the new function `json_object_new_double_fmt(double d, char *fmt)`, one can now specify what printf-compatible format string should be used to serialize this specific double. This allows for dynamic adaptation of the precision depending on the precision of the source as well as the indended usage.
This fixes #154 and #59.
=> Make serialization format of doubles configurable

.gitignore, json_object.c, json_object.h, tests/Makefile.am, tests/test_double_serializer.c, tests/test_double_serializer.expected, tests/test_double_serializer.test
As mentioned on the mailing list, I'd find it useful to be able to use the userdata field for custom data. This PR changes the default serializer for doubles to ignore the userdata again and adds API for userdata.
=> Add public API to use userdata independently of custom serializer

json_object.h
=> Include stddef.h in json_object.h

configure.ac
If we use json_inttypes.h we are going to fail when builddir != srcdir,
and since JSON_C_HAVE_INTTYPES_H is defined after the configure script
has run, including json_inttypes.h would be the equivalent on including
stdint.h anyway.
This fixes the build of json-c in the GNOME Continuous builder.
=> Use stdint.h to check for size_t size

tests/test1.c
Change %d to %zu for size_t arguments, otherwise compilation will fail with
errors like:
test1.c:70:15: error: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Werror=format=]
=> tests/tests1: fix printf format for size_t arguments

linkhash.c, linkhash.h
Doing unconditional free call if  the free callback is available instead of checking for callback  availability for every entry of hashmap
=> linkhash.c: optimised the table_free path

printbuf.c
It's possible (e.g. by using json_object_from_file() on an empty file)
to get json-c to try to use a printbuf that has never had anything
written to it. Before this change, it could access a string that
should be length zero, but was never initialized, and could
theoretically have an unexpected string.
I ran into this while using valgrind on an application's tests that sometimes
specified an empty json configuration file. So I guess the main motivation of
this PR is to shut up valgrind :)
But, I was able to come up with a sort of proof-of-concept of actual harm from the bug:
```c
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "json.h"
#include "json_util.h"
const char *test_file = "test_attack.json";
int main() {
int fd = …
```
=> initialize null terminator of new printbuf

README-WIN32.html
Updates README-WIN32.html to remove my status as a maintainer (I'm not). Also removes ancient porting notes and adds a reference to json_config.h.win32 which is where most folks should go to start with Windows issues.
=> Removes me as Win32 maintainer, because I'm not.

linkhash.h
While using the library on a 64 bit application there where problems because of a 32 bit truncation of a pointer.
This patch changes the unsigned long to the C99 uintptr_t that considers the architecture in which the library is compiled.
=> Support for 64 bit pointers on Windows

CMakeLists.txt, Makefile.am, json-c.vcxproj, json-c.vcxproj.filters, json_object.c, json_pointer.c, json_pointer.h, json_tokener.c, printbuf.c, strdup_compat.h, tests/test_json_pointer.c, vasprintf_compat.h
Adds support for calling with 'json_pointer_get(obj, "/foo/%d/%s", &res, 0, bar)'
style args.
Makes it easier for doing more dynamic stuff/magic, without
needing to use vasprintf() externally.
Other stuff is cleanup, and extend the current json_pointer test.
=> json_pointer: extend setter & getter with printf() style arguments

json_object.c, printbuf.c, printbuf.h, tests/test_printbuf.c, tests/test_printbuf.expected
Hi there! This is a performance-related patch to improve `json_object` -> string conversion.
It yields average performance gains of ~350% for large objects.
Breakdown
----------
A `perf` analysis of a tight loop around `json_object_to_json_string()` yields the following results:
As you can see the primary hotspot here is `sprintbuf()` - more specifically, `vsnprintf()` / `vfprintf()`. Digging deeper, it appears that every call to `sprintbuf()` results in a full init of a variadic list. Variadic functions in themselves are pretty slow; they become rather onerous in terms of performance when called in a tight loop, as is often the case when dumping large amounts of JSON. I took a closer look at the rest of `json-c` and found that almost every call to `sprintbuf()` does not make use of the …
=> Improve json_object -> string performance

linkhash.c
Compilation fails if C-99 mode is not switched on or present.
=> Fix compilation without C-99 option

json_object.c
If compiled on VS2015 with the default configuration, the original codebase raises error C3688: invalid literal suffix 'PRId64'; literal operator or literal operator template 'operator ""PRId64' not found. Simply adding a space before PRId64 resolves this issue.
=> Fix error C3688 when compiling on Visual Studio 2015

json_object.c
Issue originally found in the json-c 0.11 internal copy in GDAL but also found
in latest git version.
If doing things like
```
json_object* obj = json_object_new_double(1e300);
json_object_set_serializer(obj, json_object_double_to_json_string, "%f", NULL);
json_object_to_json_string(obj)
```
```
size = snprintf(buf, sizeof(buf),
format ? format :
(modf(jso->o.c_double, &dummy) == 0) ? "%.17g.0" : "%.17g",
jso->o.c_double);
```
will return a value greater than 128 since at least 300 characters are needed.
This value is then passed to printbuf_memappend(pb, buf, size); that tries to
read size bytes in buf.
So we should clamp size to sizeof(buf). And on Windows, _snprintf() returns -1
in that situation, so deal also with this case.
Fixes …
=> Fix stack buffer overflow in json_object_double_to_json_string_format()

configure.ac
This macro is obsolete since at least autoconf-2.63.
=> Replace obsolete AM_PROG_LIBTOOL

.gitignore, CMakeLists.txt
Based on this comment (https://github.com/json-c/json-c/pull/321#issuecomment-309446230) , I decided to check if it is possible to have both libjson-c.a and libjson-c.so.
Seems it is.
=> build,cmake: build,cmake: rename libjson-c-static.a to libjson-c.a

json_object.h, json_tokener.h
This allows to compile json-c as a dynamic library with Visual Studio. This is needed because declaring a function as `extern` is not enough to make this compiler export it, so the resulting library was not exporting anything. I also export a couple functions which weren't before, as I was getting undefined references otherwise.
As far as I know this should not break anything on other platforms but I didn't have time to confirm that.
=> Windows: Fix dynamic library build with Visual Studio

.travis.yml, Makefile.am, configure.ac, json_object.c, json_pointer.c, json_util.c, random_seed.c, strerror_override.c, strerror_override.h, tests/Makefile.am, tests/test_basic.test, tests/test_json_pointer.c, tests/test_util_file.c, tests/test_util_file.test
Seems some failing tests have piled up, due to a missing `set -e`
* `test_util_file` test ; the issue is that Apple linkers don't allow to override `strerror` and this seems to be locked down on travis-ci.org [ for security reasons I assume ] ; I tried some solutions from the web (like here: http://tlrobinson.net/blog/2007/12/overriding-library-functions-in-mac-os-x-the-easy-way-dyld_insert_libraries/) ; patches can be checked out here: https://github.com/commodo/json-c/commit/49ed91eb39d96ac625553843ba2c02018f601964  & https://github.com/commodo/json-c/commit/ca13901e0c37a9885fbc665c638185f0ef1c804f  ; so, trying to force the test's `strerror`  did not work for me ; they worked locally, but not on travis ;  I gave up [ after a few hours ] and resumed to go by checking specific output …
=> tests: fix tests in travis-ci.org

.travis.yml, strerror_override.h
=> strerror_override: add extern "C" and JSON_EXPORT specifiers for Visual C++ compilers

Makefile.am
`EXTRA_DIST` copies the listed directories/files from the **source** directory into the distribution.
Since the `doc` directory does not exist after running autogen + configure + make dist, the distribution tarball generation fails. Note that the `dist-hook` rule below operates on `distdir`, not on the source directory where `EXTRA_DIST` expects the existence of the `doc` folder.
In summary, even if I remove `doc` from `EXTRA_DIST`, the dist tarball will always contain the documentation (due to the `dist-hook` rule).
=> Fix make dist and make distcheck

json_object.c
Avoids undefined behavior.  Found by autofuzz.
=> Clamp double to int32 when narrowing in json_object_get_int.

configure.ac, json_object.c, json_util.c
Instead of using `sscanf()` (whose behavior is surprisingly underspecified) to parse integer values, use `strtoll()` instead.  It turns out to be much simpler, and hopefully is more portable.
=> Use strtoll() to parse ints

json_object.c
=> Fix double to int cast overflow in json_object_get_int64.

json_object.c, json_tokener.c, linkhash.c
This will make this branch compilable without errors/warnings under gcc-7. This branch is used by volkzaehler/vzlogger.
=> added fallthrough for gcc7

.gitignore, json_object.c, json_object.h, tests/Makefile.am, tests/test_deep_copy.c, tests/test_deep_copy.expected, tests/test_deep_copy.test
Seems to perform better than outputting to string and re-parsing it.
```
BENCHMARK - 1000000 iterations of 'dst2 = json_tokener_parse(json_object_get_string(src2))' took 20 seconds
BENCHMARK - 1000000 iterations of 'dst2 = json_tokener_parse(json_object_get_string(src2))' took 7 seconds
```
This function will be needed for JSON patch [RFC 6902] ; before applying a patch, a backup of the original object will be made ; in case any patch operation fails, the JSON object should not be modified at all.
This is covered in section `5.  Error Handling`
This PR also adds the `json_object_new_null()` function (which is requested here https://github.com/json-c/json-c/issues/226 ).
While copying the JSON object, it's easier to have an object-ual representation for the JSON `null`.
Signed-off-by: …
=> json_object: implement json_object_deep_copy() function

json_object.c, json_object.h
In VS 2015, the warning text is "warning C4550: expression evaluates to a function which is missing an argument list".
=> Fix a VS 2015 compiler warning.

Doxyfile, README.md
Previously a special tag was added to README.md to make this the
main page in Doxygen generated docs. When viewing the README on the
GitHub page this tag was not hidden.
After upgrading to Doxygen 1.8.8 (and above) in changeset
219025727dd7d981cf2fea7f2095570924e7bae7 a new Doxygen feature can be
used to specify the main page: Since release 1.8.3 Doxygen has a special
option to set a markdown file as main page. When using this option we
can drop the tag, making the README rendered by GitHub nice to look at.
Fixes: ae66b243690871f2daea5ae4b2a4669081d7c556
=> doc: Use other doxygen feature to specify mainpage

json_object.c, json_object.h
This comes in handy when one wants to pre-allocate memory to store a bunch of `struct json_object`, like [gdal does](https://github.com/OSGeo/gdal/blob/f8c279b1c1ae1da1b5025e2a43a1b4d99acf2852/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp#L45).
=> json_object: Add size_t json_object_sizeof()

json_object.h
Fixes a couple of compilation warnings with Visual Studio (I think, I haven't been able to test it).
=> Fix non-GNUC define for JSON_C_CONST_FUNCTION

Makefile.am
This is recommended by the [libtool manual](https://www.gnu.org/software/libtool/manual/html_node/Invoking-libtoolize.html).
```
In the future other Autotools will automatically check the contents of
AC_CONFIG_MACRO_DIRS, but at the moment it is more portable to add the
macro directory to ACLOCAL_AMFLAGS in Makefile.am, which is where the
tools currently look. If libtoolize doesn’t see AC_CONFIG_MACRO_DIRS,
it too will honour the first ‘-I’ argument in ACLOCAL_AMFLAGS when
choosing a directory to store libtool configuration macros in.  It is
perfectly sensible to use both AC_CONFIG_MACRO_DIRS and ACLOCAL_AMFLAGS,
as long as they are kept in synchronisation.
```
=> Makefile: Add ACLOCAL_AMFLAGS

json_object.c
Without this patch `libu2f-server` and `sway` may segfault during regular code execution.
=> json_object: Avoid double free (and thus a segfault) when ref_count gets < 0

Makefile.am, json_object.c
=> json_object: Avoid invalid free (and thus a segfault) when ref_count gets < 0

json_object.c, json_object_private.h
Since https://github.com/json-c/json-c/commit/9aca3b6a087a396a81d7e26f4557eb97fecc1386 it is very, very unlikely the refcount can ever go < 0.  And as `struct json_object` is an opaque pointer for the user, there are no breaks in the API / ABI.
I choose the `uint_fast` version intentionally, so there is a guarantee for getting at least 32-bit of width, but it might be wider if the underlying architecture can handle it faster than a pure uint32_t.  An unsigned 32-bit wide integer type can handle numbers up to about 4.29 billion, so overflowing the refcounter should be very unlikely, too; the assert is simply just to prevent the caller to do something really jackass.
=> json_object_private: Use unsigned 32-bit integer type for refcount

CMakeLists.txt
When building the project using cmake then installing it.  The
definitions in `json_object_iterator.h` are required but not installed
by the cmake install rule.  This patch adds the `json_object_iterator.h`
file to the list of files to install.
Signed-off-by: Keith Holman <keith.holman@windriver.com>
=> install json_object_iterator.h header file

CMakeLists.txt
1. The windows dll will output the lib and dll, and rename the static
lib will have conflict on windows.
2. Delete rename code to dismiss the conflict.
=> Resolve windows name conflict

CMakeLists.txt, README.md, appveyor.yml, cmake/Config.cmake.in, cmake/config.h.in, cmake/json_config.h.in
This patch provides a CMakeLists.txt file to build JSON-C library without relying on auto-tools support. This makes the build a bit more portable and cleaner.
It can detect headers and symbols and generate config.h header file based on those detections. It cannot yet handle ctest(1) as the testing itself depends on comparing the output against files. Testing would need some creative abuse of CMake :) This will be provided a few patches later and may possibly involve re-factoring test cases.
The patch has been tested on GCC 4.8.5 (Linux), GCC 7.2.0 (MinGW) and Microsoft Visual C++ 16.0 (2010?) locally. Also, compiles correctly on Travis CI and AppVeyor without errors.
PS: Finally, this updates the patch provided in #432 & #433 by correcting AppVeyor file. Sorry for the inconvenience. I …
=> The real CMake support

CMakeLists.txt
current CMAKE_C_FLAGS will be overwrite to "-Werror", and original c flags are lost.
this will cause compile error when compile using NDK.
=> fix c flag loss during cmake building

json_tokener.h
There’s no documentation which states the reference count of the object returned by `json_tokener_parse_ex`, nor who owns the reference (i.e. whether the object will be destroyed if `json_tokener_reset` is called or the tokener is destroyed). Document it, with what I believe to be the correct answer.
=> Document refcount of json_tokener_parse_ex return

CMakeLists.txt
Now json-c can be bundled to any cmake-based project and used with
couple lines of code:
add_subdirectory(json-c EXCLUDE_FROM_ALL)
target_link_libraries(MyProject json-c)
=> Allow use json-c cmake as subproject

README.html
=> README.html:fix link to Doxygen docs, remove WIN32 link

ChangeLog
The file still had `iso-8859-1` encoding and thus should be updated.
=> Convert ChangeLog to valid UTF-8 encoding.

CMakeLists.txt
CMake was not properly substituting the installation dir variables (they
ended up all empty), so the pkg-config results were also wrongs. For
instance cflags was: -I -I/json-c
Even though json-c was found at configure time, this obviously broke the
build of any application using it.
=> Installation directories empty with CMake in pkg-config.

CMakeLists.txt, cmake/Config.cmake.in
This patch exports the CMake install target so that the users can install the CMake module files and use them in a CMake-based project like this:
```cmake
find_package(json-c CONFIG REQUIRED)
add_executable(json_c_test json_c_test.c)
target_link_libraries(json_c_test PRIVATE json-c::json-c)
```
The `json-c` target is put under `json-c::` namespace:
https://github.com/myd7349/json-c/blob/c2036ab9fc602cca8c9f200d6fe25d443b3b169e/CMakeLists.txt#L261
If:
```cmake
target_link_libraries(json_c_test PRIVATE json-c)
```
is more preferable, we may just delete that line.
=> Install CMake module files

tests/Makefile.am
Allows the tests to pass when running `make distcheck`
This fixes the 2 broken tests I mentioned at
https://github.com/json-c/json-c/pull/499#discussion_r306998261
=> test/Makefile.am:add missing deps for test1 and test2

tests/Makefile.am
resolves #406 
I also added `-UNDEBUG` to tests/Makefile.am to make sure NDEBUG is always undefined for tests. (So if someone had debugging enabled, they won't have to re-run `configure --enable-debug=off` just to undefine it.)
Adding this arg to configure also will allow for turning on [profiling](https://sourceware.org/binutils/docs/gprof/), which can't really be used with the library by itself, afaik, but perhaps in the future a test may be added to utilize it.
=> undefine NDEBUG for tests

tests/CMakeLists.txt
Contrary to other CMAKE variables the CMAKE_C_FLAGS variable is the
composed string of flags for the C compiler. It is therefore not a list
to append to. Current implementation results in these incorrect CFLAGS,
e.g., "-O2 -g -fblahblah;-UNDEBUG". Extending the CFLAGS this way
results in the proper CFLAGS, e.g., "-O2 -g -fblahblah -UNDEBUG".
=> Properly append to CMAKE_C_FLAGS string

tests/test_parse.c, tests/test_parse.expected
update tsetcase for json_tokener_c
=> update tsetcase for tokener_c

tests/test_json_pointer.c, tests/test_json_pointer.expected
=> update pointer test case

tests/test_parse.c
```
cc -DHAVE_CONFIG_H -I. -I..  -I.. -I../tests    -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -Wall -Werror -Wcast-qual -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -D_GNU_SOURCE -D_REENTRANT -MT test_parse.o -MD -MP -MF .deps/test_parse.Tpo -c -o test_parse.o test_parse.c
test_parse.c:256:14: error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]
{ "null123" + 4,       4, 3, json_tokener_success, 1 },
~~~~~~~~~~^~~
test_parse.c:256:14: note: use array indexing to silence this warning
{ "null123" + 4,       4, 3, json_tokener_success, 1 },
^
&         [  ]
test_parse.c:258:12: error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]
{ "nullx" + 4,         2, 0, …
```
=> Fix "make check"

CMakeLists.txt, README.md
1. add doc target in cmake and use doxygen tool to get API documentation. 
```
cmake ..
make doc
```
2. add ```make doc``` description in README.md.
=> add doc target in cmake

json_object.c, json_util.c, json_util.h
This is a recent regression since commit
6359b798479d379a3202e02c6a938d9b40c0d856 which added various assert(0)
calls (often replacing return-s).
With Ming-W64 compiler, json-c build was failing with various errors of
the sort:
> /home/jehan/dev/src/json-c/json_object.c: In function 'json_object_int_inc':
> /home/jehan/dev/src/json-c/json_object.c:841:1: error: control reaches end of non-void function [-Werror=return-type]
>   841 | }
>       | ^
> In file included from /home/jehan/dev/src/json-c/json_object.c:17:
> /home/jehan/dev/src/json-c/json_object.c: In function 'json_object_get_double':
> /home/jehan/.local/share/crossroad/roads/w64/json-c/include/assert.h:76:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
>    76 | …
=> Fixes various Wreturn-type and Wimplicit-fallthrough errors on Mingw-w64

.travis.yml, CMakeLists.txt
This PR adds the coveralls auto tool to json-c.  [Coveralls](https://coveralls.io/) is a web service to help you track your code coverage over time, and ensure that all your new code is fully covered.
I have added it in [dota17/json-c](https://github.com/dota17/json-c?organization=dota17&organization=dota17) and showed a PR submission example in [here](https://github.com/dota17/json-c/pull/40). We can see the json-c's  code coverage in README.md and get the code coverage report from coveralls automatically when you submit a PR. It is a useful and helpful tool.
Following are the configuration steps：
1. Sign in the https://coveralls.io/ with github account and open the switch of json-c/json-c in [```ADD REPO``` ](https://coveralls.io/repos/new).
2. configure file: 
note: ```Compact``` means …
=> add coveralls auto tool to json-c

arraylist.c, json_object.c
Although it is currently working, it's worth to stick with the stdlib definition to avoid further problems
=> Changed order of calloc args to match stdlib

.travis.yml
coveralls-cpp is dead and does not work anymore. Fortunately there is coveralls-lcov available.
=> Fix coveralls submission.

.travis.yml, CMakeLists.txt
* Fix appending of linker flags.
* Build Doxygen documentation out-of-tree.
* Check whether BSYMBOLIC is supported by the linker.
=> Small fixes to CMakeLists

CMakeLists.txt
The default location for pkconfig files on most systems is: `${CMAKE_INSTALL_LIBDIR}/pkgconfig`
Thus the file should get installed in there by default.
=> CMake: Install pkgconfig file in proper location by default

random_seed.c
The current CPUID check seems to be reliant on the state of registers at call-time (...or something like that?), since it occasionally segfaults. Here's an example of it in a simplified context:
```c
#include <stdio.h>
static void do_cpuid(int regs[], int h)
{
/* clang-format off */
__asm__ __volatile__(
#if defined __x86_64__
"pushq %%rbx;\n"
#else
"pushl %%ebx;\n"
#endif
"cpuid;\n"
#if defined __x86_64__
"popq %%rbx;\n"
#else
"popl %%ebx;\n"
#endif
: "=a"(regs[0]), [ebx] "=r"(regs[1]), "=c"(regs[2]), "=d"(regs[3])
: "a"(h));
/* clang-format on */
}
static int has_rdrand(void)
{
// CPUID.01H:ECX.RDRAND[bit 30] == 1
int regs[4];
do_cpuid(regs, 1);
return (regs[2] & (1 << 30)) != 0;
}
static int get_rdrand_seed(void)
{
int _eax;
// rdrand eax
/* clang-format off */
__asm__ __volatile__("1: …
```
=> Fix segmentation fault in CPUID check

arraylist.c, linkhash.c, printbuf.c
I have discovered a way to trigger an out of boundary write while parsing a huge json file through a malicious input source. It can be triggered if an attacker has control over the input stream or if a huge load during filesystem operations can be triggered.
Preparation:
``$ dd if=/dev/zero of=poc.json bs=1 count=1 seek=2147483647``
Code to exploit:
```
#include <json-c/json_util.h>
#include <unistd.h>
int main() {
json_object_from_fd(STDIN_FILENO);
return 0;
}
```
Proof of Concept:
``(dd if=poc.json bs=4096; sleep 1; dd if=test.json bs=10) 2>/dev/null | ./test``
Explanation:
The problem manifests itself in printbuf_memappend. On properly crafted values, p->bpos + size + 1 can overflow, which leads to the assumption that p->size is still large enough. In normal circumstances, this does …
=> Prevent out of boundary write on malicious input

json_object.c, tests/test_set_serializer.c, tests/test_set_serializer.expected
A custom double formatter can lead to truncation of the rest of the
JSON document.
If a custom formatter completely fills the buffer used by snprintf
with a trailing dot or comma and the formatting option
JSON_C_TO_STRING_NOZERO has been specified, then an iterator moves
past the ending '\0' (off-by-one buffer overflow) to set an
additional '\0' and adds the first '\0' into the printbuf.
Since '\0' will eventually be considered the terminating character
of the complete printbuf result, all trailing characters are lost.
This leads to an incomplete JSON string as can be seen with the
test case.
The off-by-one can be noticed if compiled with address sanitizer.
Since this is a very special case and a malformed formatter could
do way more harm and is the responsibility of the user of this …
=> Prevent truncation on custom double formatters.

CMakeLists.txt, README.md, tests/test_double_serializer.c
Using thread-local storage may not be desired in all environments and/or use-cases, thus there should be an option to disable its use on purpose.
Fixes #451.
=> Add an option to disable the use of thread-local storage.

CMakeLists.txt, Doxyfile.in
This allows to build the Doxygen documentation out-of-tree properly.
=> CMake: Fix out-of-tree build for Doxygen documentation.

CMakeLists.txt, README.md
json-c has symbol collisions with other popular C JSON libraries.
To prevent random crashes in downstream applications that may use a
library which depends on json-c, the solution is to statically link
libjson-c.a into those libraries.
`-fPIC`/`-fPIE` is required when building a `.a` so it can be linked
into a `.so`.
=> Issue #508: `-fPIC` to link libjson-c.a with libs

json_tokener.c
`tolower` expects an `unsigned char` or the special value `EOF`.
=> Cast to unsigned char instead of int when calling tolower (Fixes #645)

doc/Doxyfile.in
Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/) I noticed that `json-c` could not be built reproducibly.
This is because it used the full, absolute path name as a (sanitised) input to a filename, resulting in some binary package containing, for example:
```
/usr/share/doc/libjson-c-dev/html/md__build_1st_json-c-0_815_issues_closed_for_0_813.html
^^^^^^^^^^^^^^^^^^^^^^
```
or
```
/usr/share/doc/libjson-c-dev/html/md__build_2_json-c-0_815_2nd_issues_closed_for_0_813.html
^^^^^^^^^^^^^^^^^^^^^^^^
```
These differing values are based on the path in which `json-c` is built. This was originally filed in Debian as [#966657](https://bugs.debian.org/966657).
=> Make the documentation build reproducibly

random_seed.c
The json-c library is used in cryptsetup for LUKS2 header information.
Since cryptsetup can be called very early during boot, the developers
avoid getrandom() calls in their own code base for now. [1]
Introducing a blocking getrandom() call in json-c therefore introduces
this issue for cryptsetup as well. Even though cryptsetup issues do not
have to be json-c issues, here is my proposal:
Let's use a non-blocking call, falling back to other sources if the call
would block. Since getrandom() accesses urandom, it must mean that we
are in an early boot phase -- otherwise the call would not block
according to its manual page.
As stated in manual page of random(4), accessing /dev/urandom won't
block but return weak random numbers, therefore this fallback would work
for json-c.
While at it, …
=> Use GRND_NONBLOCK with getrandom.

random_seed.c
Casting time(2) return value to int and multiplying the result with
such a constant will definitely lead to a signed overflow by this day.
Since signed overflows are undefined behaviour in C, avoid this.
Casting to unsigned is more than enough since the upper bits of a
64 bit time_t value will be removed with the int conversion anyway.
=> Prevent signed overflow in get_time_seed

json_object.c
Strings that long cannot be parsed through files or tokeners by now.
Prepare for the future and protect API calls which would allow
addition of such strings into data structures.
=> Limit strings at INT_MAX length

arraylist.c, tests/test1.c
The array_list_new2 function, which is externally reachable through
json_object_new_array_ext, does not check if specified initial size
actually fits into memory on 32 bit architectures.
It also allows negative values, which could lead to an overflow on these
architectures as well. I have added test cases for these situations.
While at it, also protect array_list_shrink against too large
empty_slots argument. No test added because it takes a huge length
value, therefore a lot of items within the array, to overflow the
calculation. In theory this affects 64 bit sytems as well, but since the
arraylist API is not supposed to be used by external applications
according to its header file, the call is protected due to int
limitation of json_object_array_shrink.
=> Validate size arguments in arraylist functions.

json_tokener.c
The allocation of printbuffer could fail. Also avoid strdup for
setlocale return value to prevent allocation issues in the first place.
=> Handle more allocation failures in json_tokener* functions

tests/test1.c
SIZEOF_SIZE_T might be only defined in config.h.
Include config.h for these systems to pass tests which are only
supposed to be run on 32 bit systems.
Fixes issue #666.
=> Fixed test1 regression.

CMakeLists.txt
Fixes the following warning:
json_pointer.c:230:7: warning: implicit declaration of function
'vasprintf' is invalid in C99 [-Wimplicit-function-declaration]
rc = vasprintf(&path_copy, path_fmt, args);
=> fix compilation with clang

random_seed.c
CMake Release configuration add the `-Werror` flag, which fails the compilation if there any warning. There is an only one - unused variable.
Please let compilations succeed with Release configuration.
Build logs:
```bash
user@buildhost MINGW64 ~/json-c
$ mkdir build && cd $_
user@buildhost MINGW64 ~/json-c/build
$ cmake .. -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 10.2.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/resource.h
-- Looking for sys/resource.h - not found
-- Wrote …
```
=> Fix unused variable for Win32 build in random_seed.c

.gitignore, CMakeLists.txt, json.h.cmakein, tests/CMakeLists.txt
Some users may not want to included it in their build/system. So allow a
cmake symbol to disable it.
A user can do 'cmake -DDISABLE_JSON_POINTER=ON <json_c_root_dir>' and
disable the json_pointer functionality. That saves about 17 KB (on an
x86_64) machine. This may be useful on smaller embedded systems; even
though the saving would be fewer kilobytes.
One thing that also needs to change a bit, is that the 'json.h' be
autogenerated via cmake, in order to conditionally include that
"json_pointer.h" file.
=> [RFC] json_pointer: allow the feature to be disabled

CMakeLists.txt, debug.h, json_c_version.h, json_types.h, printbuf.h
Add JSON_C_DLL flag to avoid target exe file export JSON functions.
=> To avoid target exe file export JSON functions.

.clang-format
This is to fix the behavior that might've changed between older versions of clang-format, I'm not sure.
Regardless, version 10 (and possibly earlier, I didn't check) tries to put the bracket on the same line as case without this.
=> Add AfterCaseLabel to .clang-format

json_tokener.c
The failure path taken in the event of printbuf_new() returning NULL
calls free() on tok->stack after already having freed tok. Swap the
order of the two calls to fix an obvious memory access violation.
Fixes: bcb6d7d3474b ("Handle allocation failure in json_tokener_new_ex")
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>
=> Fix use-after-free in json_tokener_new_ex()

json_object.c
This makes Coverity Scan happier since it believes that the initial
check ``if (!src->_userdata && !src->_user_delete)`` could mean that
src->_user_data may be nullptr.
=> json_object_copy_serializer_data(): add assertion

json_util.c
Was detected by Coverity Scan when analyzing GDAL's code base which has
a copy of json-c
=> json_type_to_name(): use correct printf() formatter

json_object.c
Current behaviour is perfectly valid, since wrap-over upon overflow is
well defined behaviour for unsigned types, but it is nevertheless nice to be
able to build with -fsanitize=undefined,unsigned-integer-overflow
There is no significant effect on the generated assembly as can be seen
on the diff of objdump -d output on a optimized build (the compiler
just decided to switch the order of a comparison):
```
@@ -135,8 +135,8 @@
1d0:	0f 84 70 ff ff ff    	je     146 <json_escape_str+0x146>
1d6:	4c 3b 24 24          	cmp    (%rsp),%r12
1da:	0f 85 2d ff ff ff    	jne    10d <json_escape_str+0x10d>
- 1e0:	49 39 f4             	cmp    %rsi,%r12
- 1e3:	0f 87 b7 00 00 00    	ja     2a0 <json_escape_str+0x2a0>
+ 1e0:	4c 39 e6             	cmp    %r12,%rsi
+ 1e3:	0f 82 b7 00 00 00    	jb     2a0 …
```
=> json_escape_str(): avoid harmless unsigned integer overflow

vasprintf_compat.h
Systems without vasprintf fall back to implementation in header file
vasprintf_compat.h. This version could run into heap overflow issues
with very long arguments or formats provoking a lot of output.
The vsnprintf function returns a negative value if more than INT_MAX
characters would be written since its int return type could not
handle this (and %n couldn't handle it either).
Before testing for a possible error value the additional char for
\0 is already added. A -1 error code would not be detected.
Increment only after implicitly casting to an unsigned value to avoid
signed integer overflow if INT_MAX has been returned.
Use va_copy to duplicate the original ap argument for multiple uses
on non-WIN32 systems. At least with glibc the test suite would fail
because the arguments are not …
=> vasprintf(): avoid out of memory accesses

printbuf.c
If invalid arguments are passed to printbuf functions return -1 to
protect printbuf internals.
=> printbuf: do not allow invalid arguments

printbuf.c
It is possible to have a printbuf with "gaps", i.e. areas within the
print buffer which have not been initialized by using printbuf_memset.
Always clear memory in such cases.
Example:
```
struct printbuf *pb = printbuf_new();
printbuf_memset(pb, 10, 'a', 2);
```
In this case pb->buf[0] is '\0' but pb->buf[1] up to pb->buf[9] are
not set. The length would be 12 due to successful printbuf_memset.
=> printbuf_memset(): set gaps to zero

printbuf.c
If errors occur in printbuf_memappend, then these errors should be
propagated through sprintbuf to indicate the error to the user.
Proof of Concept:
```
#include <err.h>
#include <limits.h>
#include <stdio.h>
#include "json.h"
int
main(void) {
struct printbuf *pb;
if ((pb = printbuf_new()) == NULL)
err(1, "printbuf_new");
if (printbuf_memset(pb, INT_MAX - 9, 'a', 1) < 0)
errx(1, "printbuf_memset");
printf("length: %d\n", printbuf_length(pb));
printf("sprintbuf: %d\n", sprintbuf(pb, "string too long"));
printf("length: %d\n", printbuf_length(pb));
printbuf_free(pb);
return 0;
}
```
You can see that sprintbuf does not return an error but length is still
the same, i.e. the string "string too long" has not been appended.
I would like to add this as a unit test but it really depends on the …
=> sprintbuf(): handle printbuf_memappend errors

printbuf.c
The POSIX specification states that vsnprintf returns "a negative value"
in case of error, but the code checks explicitly only for -1.
=> sprintbuf(): test for all vsnprintf error values

json_object.c, json_util.c
Error messages did not reflect actual function names.
This pull request is separated from documentation fixes in case these
messages are supposed to look this way for historical reasons or
compatibility.
=> Fix error messages

json_object.c
this way it complies with the other #error usages
shoutout to [c3h2-ctf](https://twitter.com/c3h2_ctf)
=> Code style: removed unneeded double-quotes

apps/json_parse.c
missing 'FALLTHRU' added to sort out error messages when using "-Werror=implicit-fallthrough" flag
=> Issue #768

json_object.c
When a json string object is updated with a bigger string, a new
malloc'ed buffer is used to store the new string and it's size is made
negative to indicate that an external buffer is in use.
When that same json string object get's updated again with an empty
stirng (size = 0), the new external malloc'ed buffer is still used.
But the fact that the new size value is not negative removes the
indicator that the externally malloc'ed buffer is used.
This becomes a problem when the object get's updated again with any
other string, because a new buffer will be malloced and linked to the
object while to old one won't be free'd.
This causes a memory leak when updating a json string with
json_object_set_stirng() which has previously been updated
with an empty string.
Example:
--
obj = …
=> Fix memory leak with emtpy strings in json_object_set_string

json_util.c, printbuf.c, tests/test_util_file.expected
If the input file is too large to fit into a printbuf then return an
error value instead of silently truncating the parsed content.
This introduces errno handling into printbuf to distinguish between an
input file being too large and running out of memory.
=> json_object_from_fd_ex: fail if file is too large

doc/Doxyfile.in, tests/test_deep_copy.c, tests/test_deep_copy.expected
Do not fix typos from past commits found in release notes.
```
$ codespell 
./issues_closed_for_0.15.md:80: informations ==> information
./issues_closed_for_0.14.md:98: valuse ==> values, value
./issues_closed_for_0.14.md:104: upate ==> update
./issues_closed_for_0.14.md:132: retuns ==> returns
./issues_closed_for_0.13.md:154: successed ==> succeeded, success, successful
./issues_closed_for_0.13.md:160: doubel ==> double
./issues_closed_for_0.13.md:178: representaion ==> representation
$ 
```
=> Fix typos found by codespell

json_inttypes.h, json_pointer.c, json_util.c, tests/test1.c, tests/test4.c, tests/test_cast.c, tests/test_charcase.c, tests/test_parse.c, tests/test_printbuf.c, tests/test_util_file.c
Fixes
json_util.c:63:35: error: a function declaration without a prototype is deprecated in all versions of C [-We
rror,-Wstrict-prototypes]
const char *json_util_get_last_err()
^
void
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Fix build with clang-15+

random_seed.c
It warns about the return of time() being truncated to 32 bit, which is
not an issue here.
(this warning was emitted because of the https://github.com/OSGeo/gdal
project embedding a copy of libjson-c and running Coverity Scan
analysis)
=> get_time_seed(): silence warning emitted by Coverity Scan static analyzer

CMakeLists.txt
The warning is as follows:
```
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
```
Solution: set it at 2.8.12
=> Problem: modern CMake warns about version 2.8

CMakeLists.txt
Solution: set it explictly to OLD behavior
=> Problem: cmake 3.25.1 warns about CMP0042 not being set

random_seed.c
Some CPUs advertise RDRAND in CPUID, but return 0xFFFFFFFF unconditionally.  To avoid locking up later, test RDRAND during initialization, and if it returns 0xFFFFFFFF, mark it as nonexistent.
Also fix a possible segmentation fault in CPUID check.
This commit is a squashed backport of the following commits on the master branch:
* 0e5bbcaa162ac7850eb4fcd8f91391837d0efb50
* 4d36b0287d3ab0912ba8a4790340ca099960b2b0
* 80863140263be5f2dc630938ed8f0066f8a1ab43
=> json-c-0.14: Detect broken RDRAND during initialization.

random_seed.c
Some CPUs advertise RDRAND in CPUID, but return 0xFFFFFFFF unconditionally.  To avoid locking up later, test RDRAND during initialization, and if it returns 0xFFFFFFFF, mark it as nonexistent.
Also fix a possible segmentation fault in CPUID check.
This commit is a squashed and slightly modified backport of the following commits on the master branch:
* 0e5bbcaa162ac7850eb4fcd8f91391837d0efb50
* 4d36b0287d3ab0912ba8a4790340ca099960b2b0
* 80863140263be5f2dc630938ed8f0066f8a1ab43
=> json-c-0.13.x: Detect broken RDRAND during initialization.

json_tokener.c, json_tokener.h
Do not silently truncate values or skip entries if out of memory errors
occur.
Proof of Concept:
- Create poc.c, a program which creates an eight megabyte large json
object with key "A" and a lot of "B"s as value, one of them is
UTF-formatted:
```c
#include <err.h>
#include <stdio.h>
#include <string.h>
#include "json.h"
#define STR_LEN (8 * 1024 * 1024)
#define STR_PREFIX "{ \"A\": \""
#define STR_SUFFIX "\\u0042\" }"
int main(void) {
char *str;
struct json_tokener *tok;
struct json_object *obj;
if ((tok = json_tokener_new()) == NULL)
errx(1, "json_tokener_new");
if ((str = malloc(STR_LEN)) == NULL)
err(1, "malloc");
memset(str, 'B', STR_LEN);
memcpy(str, STR_PREFIX, sizeof(STR_PREFIX) - 1);
memcpy(str + STR_LEN - sizeof(STR_SUFFIX), STR_SUFFIX, sizeof(STR_SUFFIX));
obj = …
```
=> json_tokener_parse_ex: handle out of memory errors

apps/json_parse.c, json_object.c, json_object.h
This option enable color in json_object_to_json_string_ext.
I've try to made something similar to jq output,
but I color true/false and null in purple,
as it's what is common color scheme used in programing language in emacs.
also add a '-c' option into json_parser to test it.
note: that I could have done a color() function similar to
what is done with indent(), but as the code is pretty small
I've keep it as it. so if you want  me to use a subfunction
tell me and I'll do it.
Signed-off-by: Matthias Gatto <matthias.gatto@protonmail.com>
=> add JSON_C_TO_STRING_COLOR option

CMakeLists.txt, arraylist.c, arraylist.h, json-c.sym, json.h.cmakein, json_object.c, json_object.h, json_object_private.h, json_patch.c, json_patch.h, json_pointer.c, json_pointer.h, json_pointer_private.h, tests/CMakeLists.txt, tests/json_patch_spec_tests.json, tests/json_patch_tests.json, tests/test1.c, tests/test_json_patch.c, tests/test_json_patch.expected, tests/test_json_patch.test, tests/test_json_pointer.c
Initially I wanted to also do a function that generates the JSON patch from
two JSON documents, but even just applying the JSON patch was a bit of
work, especially when needing to satisfy all the test-cases.
This change defines all the operation in the RFC6902. The addition isn't
too big (for the json_patch_apply() function), as part of the heavy lifting
is also done by JSON pointer logic.
All the ops were tested with the test-cases defined at:
https://github.com/json-patch/json-patch-tests
RFC6902: https://tools.ietf.org/html/rfc6902
However, in order to properly support JSON patch:
* json_object_array_insert_idx() is needed in the JSON object API
* this changeset also changes [slightly] the behavior of `json_object_set{f}()` ; I figured, it may be still doable; I can revert that …
=> json_patch: add first implementation only with patch application

CMakeLists.txt, cmake/json_config.h.in, json_inttypes.h
adding stdint typedefs
and if you like to, you could add
```c
#if defined (_MSC_VER) && _MSC_VER < 1600
#define MISSING_STDINT_H
#endif
```
up front...
Feel free to close this PR if somewhere it is explicit said that the compiled json-c library may not be used with that old compilers.
=> Let json-c be used with obsolete compilers

CMakeLists.txt, tests/CMakeLists.txt
These policies were all introduced before CMake 3.9, so they will automatically be initialized to the new behavior when requesting a minimum version of 3.9.
=> CMake: remove needless policy setting

fuzz/tokener_parse_ex_fuzzer.cc
This commit aims to resolve to 2 possible typos in variable/API names in commit 558d48a6 that causes `tokener_parse_ex_fuzzer.c` to fail to compile.
=> Resolve build issue in tokener_parse_ex_fuzzer.c

fuzz/tokener_parse_ex_fuzzer.cc
Add checking for type of parsed object in `tokener_parse_ex_fuzzer.cc` like below:
```
if (json_object_is_type(obj, json_type_object)) {
json_object_object_foreach(obj, key, val) {
(void)json_object_get_type(val);
(void)json_object_get_string(val);
}
}
```
I think checking the type of `obj` is `json_type_object` is enough for the`tokener_parse_ex_fuzzer.cc`.
With this change, the fuzzer(libfuzzer) will no longer terminate upon execution but will instead carry out fuzzing as expected.
For reference, the fuzzer doesn't raise a null-deref issue immediately post-execution, as shown below:
```
$ python infra/helper.py run_fuzzer json-c tokener_parse_ex_fuzzer
INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e …
```
=> Add type checking for parsed objects in tokener_parse_ex_fuzzer

json_pointer.c
Fix the following build failure with gcc 5:
```
/home/thomas/autobuild/instance-2/output-1/build/json-c-0.17/json_pointer.c: In function 'json_pointer_result_get_recursive': /home/thomas/autobuild/instance-2/output-1/build/json-c-0.17/json_pointer.c:193:25: error: 'idx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
res->index_in_parent = idx;
^
```
Fixes:
- http://autobuild.buildroot.org/results/523b35a979d59121fe4e18c38171792b06233940/
=> json_pointer.c: initialize idx

random_seed.c
Coverity Scan warns about the use of open() after stat() being a potential TOCTOU (Time of check time of use) issue. But here there is no such issue.
=> random_seed.c: add a Coverity Scan suppression

json_util.c, random_seed.c, snprintf_compat.h, tests/test_util_file.c, vasprintf_compat.h
The latter is the proper macro defined by Windows headers.
Fixes compilation under at least clang-cl which mandates function declarations.
As an aside, this issue is hidden under MinGW because unistd.h there includes io.h, which defines read, write, and so forth.
=> rename WIN32 to _WIN32

json_tokener.h
Before: "Parser a json_object [...]".
After: "Parse a json_object [...]".
Thanks for the library.
=> json_tokener.h: json_tokener_parse_verbose: fix typo

json_tokener.c
`duplocale()` can return NULL, with errno set to ENOMEM. In this case, bail out and set the current error code to `json_tokener_error_memory`.
=> Handle yet another out-of-memory condition.

ChangeLog
The change log's year timestamp for the 0.18 release is a typo and confused me for a moment looking it over. This PR fixes that.
=> Correct year in changelog for 0.18 release

README.md
Under the "Usage"-section some text is erroneously underlined, because some `a`-tags aren't closed. All this pull-request does is close them.
=> Fix underline bug in README

json_tokener.c
Similarly to glibc's free, make json_tokener_free(NULL) a no-op, to simplify cleanup paths.
=> Handle NULL gracefully in json_tokener_free

linkhash.h
making the definition of `_LH_INLINE` depending on `__STDC_VERSION__`, not on a specific compiler, fixing the following:
~~~
In file included from /usr/include/json-c/json.h:32,
from conftest.c:115:
/usr/include/json-c/linkhash.h:332:19: error: expected ';' before 'unsigned'
332 | static _LH_INLINE unsigned long lh_get_hash(const struct lh_table *t, const void *k)
|                   ^~~~~~~~
~~~
=> fix linkhash breaking -std=c89

json_util.c, linkhash.c
build break if mingw-w64 on MacOSX
cmakelists.txt has add_definitions(-DWIN32_LEAN_AND_MEAN) and add_subdirectory(json-c)
=> fix macro WIN32_LEAN_AND_MEAN redefined
